#!/bin/bash

viewer() { touch /tmp/jj.dot /tmp/jj.png; kview /tmp/jj.png; }
draw() { dot -Tpng /tmp/jj.dot -o /tmp/jj.png; }
changing() { inotifywait -e close /tmp/jj.dot; }

monitor() {
  viewer &
  while changing; do draw; done &
}

run() {
  make -C build; build/jj
}
