#!/bin/bash

viewer() { touch /tmp/jj.out /tmp/jj.png; kview /tmp/jj.png; }
draw() { dot -Tpng /tmp/jj.out -o /tmp/jj.png; }
changing() { inotifywait /tmp/jj.out; }

run() {
  viewer &
  while changing; do draw; done &
  build/jj
}
